# Generated by Django 5.0.1 on 2026-01-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('dog', 'Cachorro'), ('cat', 'Gato'), ('bird', 'Pássaro'), ('rabbit', 'Coelho'), ('chicken', 'Galinha'), ('hamster', 'Hamster'), ('other', 'Outros')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Animal Type',
                'verbose_name_plural': 'Animal Types',
                'db_table': 'animal_types',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('keepsitter', 'KeepSitter'), ('keephost', 'KeepHost'), ('keepwalk', 'KeepWalk')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
                'db_table': 'service_types',
            },
        ),
        migrations.AddField(
            model_name='petsitter',
            name='about',
            field=models.TextField(blank=True, default='', help_text='About the petsitter, their experience, etc.'),
        ),
        migrations.AddField(
            model_name='petsitter',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Location/Address of the petsitter', max_length=255),
        ),
        migrations.AddField(
            model_name='petsitter',
            name='other_animals',
            field=models.CharField(blank=True, help_text='Other animals if "Outros" is selected', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='petsitter',
            name='animal_types',
            field=models.ManyToManyField(help_text='Types of animals the petsitter can care for', related_name='petsitters', to='users.animaltype'),
        ),
        migrations.AddField(
            model_name='petsitter',
            name='service_types',
            field=models.ManyToManyField(help_text='Services offered by the petsitter', related_name='petsitters', to='users.servicetype'),
        ),
    ]
